import 'subdivision.dart';

/// Subdivisions keyed by country ISO code.
const Map<String, List<Subdivision>> allSubdivisions = {
  // ═══════════════════════════════════════════════════════════════════
  // UNITED STATES — 50 states with flag codes
  // ═══════════════════════════════════════════════════════════════════
  'US': [
    Subdivision(name: 'Alabama', capital: 'Montgomery', flagCode: 'us-al'),
    Subdivision(name: 'Alaska', capital: 'Juneau', flagCode: 'us-ak'),
    Subdivision(name: 'Arizona', capital: 'Phoenix', flagCode: 'us-az'),
    Subdivision(name: 'Arkansas', capital: 'Little Rock', flagCode: 'us-ar'),
    Subdivision(name: 'California', capital: 'Sacramento', flagCode: 'us-ca'),
    Subdivision(name: 'Colorado', capital: 'Denver', flagCode: 'us-co'),
    Subdivision(name: 'Connecticut', capital: 'Hartford', flagCode: 'us-ct'),
    Subdivision(name: 'Delaware', capital: 'Dover', flagCode: 'us-de'),
    Subdivision(name: 'Florida', capital: 'Tallahassee', flagCode: 'us-fl'),
    Subdivision(name: 'Georgia', capital: 'Atlanta', flagCode: 'us-ga'),
    Subdivision(name: 'Hawaii', capital: 'Honolulu', flagCode: 'us-hi'),
    Subdivision(name: 'Idaho', capital: 'Boise', flagCode: 'us-id'),
    Subdivision(name: 'Illinois', capital: 'Springfield', flagCode: 'us-il'),
    Subdivision(name: 'Indiana', capital: 'Indianapolis', flagCode: 'us-in'),
    Subdivision(name: 'Iowa', capital: 'Des Moines', flagCode: 'us-ia'),
    Subdivision(name: 'Kansas', capital: 'Topeka', flagCode: 'us-ks'),
    Subdivision(name: 'Kentucky', capital: 'Frankfort', flagCode: 'us-ky'),
    Subdivision(name: 'Louisiana', capital: 'Baton Rouge', flagCode: 'us-la'),
    Subdivision(name: 'Maine', capital: 'Augusta', flagCode: 'us-me'),
    Subdivision(name: 'Maryland', capital: 'Annapolis', flagCode: 'us-md'),
    Subdivision(name: 'Massachusetts', capital: 'Boston', flagCode: 'us-ma'),
    Subdivision(name: 'Michigan', capital: 'Lansing', flagCode: 'us-mi'),
    Subdivision(name: 'Minnesota', capital: 'Saint Paul', flagCode: 'us-mn'),
    Subdivision(name: 'Mississippi', capital: 'Jackson', flagCode: 'us-ms'),
    Subdivision(name: 'Missouri', capital: 'Jefferson City', flagCode: 'us-mo'),
    Subdivision(name: 'Montana', capital: 'Helena', flagCode: 'us-mt'),
    Subdivision(name: 'Nebraska', capital: 'Lincoln', flagCode: 'us-ne'),
    Subdivision(name: 'Nevada', capital: 'Carson City', flagCode: 'us-nv'),
    Subdivision(name: 'New Hampshire', capital: 'Concord', flagCode: 'us-nh'),
    Subdivision(name: 'New Jersey', capital: 'Trenton', flagCode: 'us-nj'),
    Subdivision(name: 'New Mexico', capital: 'Santa Fe', flagCode: 'us-nm'),
    Subdivision(name: 'New York', capital: 'Albany', flagCode: 'us-ny'),
    Subdivision(name: 'North Carolina', capital: 'Raleigh', flagCode: 'us-nc'),
    Subdivision(name: 'North Dakota', capital: 'Bismarck', flagCode: 'us-nd'),
    Subdivision(name: 'Ohio', capital: 'Columbus', flagCode: 'us-oh'),
    Subdivision(name: 'Oklahoma', capital: 'Oklahoma City', flagCode: 'us-ok'),
    Subdivision(name: 'Oregon', capital: 'Salem', flagCode: 'us-or'),
    Subdivision(name: 'Pennsylvania', capital: 'Harrisburg', flagCode: 'us-pa'),
    Subdivision(name: 'Rhode Island', capital: 'Providence', flagCode: 'us-ri'),
    Subdivision(name: 'South Carolina', capital: 'Columbia', flagCode: 'us-sc'),
    Subdivision(name: 'South Dakota', capital: 'Pierre', flagCode: 'us-sd'),
    Subdivision(name: 'Tennessee', capital: 'Nashville', flagCode: 'us-tn'),
    Subdivision(name: 'Texas', capital: 'Austin', flagCode: 'us-tx'),
    Subdivision(name: 'Utah', capital: 'Salt Lake City', flagCode: 'us-ut'),
    Subdivision(name: 'Vermont', capital: 'Montpelier', flagCode: 'us-vt'),
    Subdivision(name: 'Virginia', capital: 'Richmond', flagCode: 'us-va'),
    Subdivision(name: 'Washington', capital: 'Olympia', flagCode: 'us-wa'),
    Subdivision(name: 'West Virginia', capital: 'Charleston', flagCode: 'us-wv'),
    Subdivision(name: 'Wisconsin', capital: 'Madison', flagCode: 'us-wi'),
    Subdivision(name: 'Wyoming', capital: 'Cheyenne', flagCode: 'us-wy'),
  ],

  // ═══ CANADA — 13 provinces & territories ═══
  'CA': [
    Subdivision(name: 'Alberta', capital: 'Edmonton'),
    Subdivision(name: 'British Columbia', capital: 'Victoria'),
    Subdivision(name: 'Manitoba', capital: 'Winnipeg'),
    Subdivision(name: 'New Brunswick', capital: 'Fredericton'),
    Subdivision(name: 'Newfoundland and Labrador', capital: 'St. John\'s'),
    Subdivision(name: 'Northwest Territories', capital: 'Yellowknife'),
    Subdivision(name: 'Nova Scotia', capital: 'Halifax'),
    Subdivision(name: 'Nunavut', capital: 'Iqaluit'),
    Subdivision(name: 'Ontario', capital: 'Toronto'),
    Subdivision(name: 'Prince Edward Island', capital: 'Charlottetown'),
    Subdivision(name: 'Quebec', capital: 'Quebec City'),
    Subdivision(name: 'Saskatchewan', capital: 'Regina'),
    Subdivision(name: 'Yukon', capital: 'Whitehorse'),
  ],

  // ═══ UNITED KINGDOM — 4 constituent countries ═══
  'GB': [
    Subdivision(name: 'England', capital: 'London', flagCode: 'gb-eng'),
    Subdivision(name: 'Scotland', capital: 'Edinburgh', flagCode: 'gb-sct'),
    Subdivision(name: 'Wales', capital: 'Cardiff', flagCode: 'gb-wls'),
    Subdivision(name: 'Northern Ireland', capital: 'Belfast', flagCode: 'gb-nir'),
  ],

  // ═══ AUSTRALIA — 6 states + 2 territories ═══
  'AU': [
    Subdivision(name: 'New South Wales', capital: 'Sydney'),
    Subdivision(name: 'Victoria', capital: 'Melbourne'),
    Subdivision(name: 'Queensland', capital: 'Brisbane'),
    Subdivision(name: 'South Australia', capital: 'Adelaide'),
    Subdivision(name: 'Western Australia', capital: 'Perth'),
    Subdivision(name: 'Tasmania', capital: 'Hobart'),
    Subdivision(name: 'Northern Territory', capital: 'Darwin'),
    Subdivision(name: 'Australian Capital Territory', capital: 'Canberra'),
  ],

  // ═══ INDIA — 28 states ═══
  'IN': [
    Subdivision(name: 'Andhra Pradesh', capital: 'Amaravati'),
    Subdivision(name: 'Arunachal Pradesh', capital: 'Itanagar'),
    Subdivision(name: 'Assam', capital: 'Dispur'),
    Subdivision(name: 'Bihar', capital: 'Patna'),
    Subdivision(name: 'Chhattisgarh', capital: 'Raipur'),
    Subdivision(name: 'Goa', capital: 'Panaji'),
    Subdivision(name: 'Gujarat', capital: 'Gandhinagar'),
    Subdivision(name: 'Haryana', capital: 'Chandigarh'),
    Subdivision(name: 'Himachal Pradesh', capital: 'Shimla'),
    Subdivision(name: 'Jharkhand', capital: 'Ranchi'),
    Subdivision(name: 'Karnataka', capital: 'Bengaluru'),
    Subdivision(name: 'Kerala', capital: 'Thiruvananthapuram'),
    Subdivision(name: 'Madhya Pradesh', capital: 'Bhopal'),
    Subdivision(name: 'Maharashtra', capital: 'Mumbai'),
    Subdivision(name: 'Manipur', capital: 'Imphal'),
    Subdivision(name: 'Meghalaya', capital: 'Shillong'),
    Subdivision(name: 'Mizoram', capital: 'Aizawl'),
    Subdivision(name: 'Nagaland', capital: 'Kohima'),
    Subdivision(name: 'Odisha', capital: 'Bhubaneswar'),
    Subdivision(name: 'Punjab', capital: 'Chandigarh'),
    Subdivision(name: 'Rajasthan', capital: 'Jaipur'),
    Subdivision(name: 'Sikkim', capital: 'Gangtok'),
    Subdivision(name: 'Tamil Nadu', capital: 'Chennai'),
    Subdivision(name: 'Telangana', capital: 'Hyderabad'),
    Subdivision(name: 'Tripura', capital: 'Agartala'),
    Subdivision(name: 'Uttar Pradesh', capital: 'Lucknow'),
    Subdivision(name: 'Uttarakhand', capital: 'Dehradun'),
    Subdivision(name: 'West Bengal', capital: 'Kolkata'),
  ],

  // ═══ MEXICO — 32 states ═══
  'MX': [
    Subdivision(name: 'Aguascalientes', capital: 'Aguascalientes'),
    Subdivision(name: 'Baja California', capital: 'Mexicali'),
    Subdivision(name: 'Baja California Sur', capital: 'La Paz'),
    Subdivision(name: 'Campeche', capital: 'San Francisco de Campeche'),
    Subdivision(name: 'Chiapas', capital: 'Tuxtla Gutiérrez'),
    Subdivision(name: 'Chihuahua', capital: 'Chihuahua'),
    Subdivision(name: 'Coahuila', capital: 'Saltillo'),
    Subdivision(name: 'Colima', capital: 'Colima'),
    Subdivision(name: 'Durango', capital: 'Victoria de Durango'),
    Subdivision(name: 'Guanajuato', capital: 'Guanajuato'),
    Subdivision(name: 'Guerrero', capital: 'Chilpancingo'),
    Subdivision(name: 'Hidalgo', capital: 'Pachuca'),
    Subdivision(name: 'Jalisco', capital: 'Guadalajara'),
    Subdivision(name: 'Mexico State', capital: 'Toluca'),
    Subdivision(name: 'Mexico City', capital: 'Mexico City'),
    Subdivision(name: 'Michoacán', capital: 'Morelia'),
    Subdivision(name: 'Morelos', capital: 'Cuernavaca'),
    Subdivision(name: 'Nayarit', capital: 'Tepic'),
    Subdivision(name: 'Nuevo León', capital: 'Monterrey'),
    Subdivision(name: 'Oaxaca', capital: 'Oaxaca de Juárez'),
    Subdivision(name: 'Puebla', capital: 'Puebla'),
    Subdivision(name: 'Querétaro', capital: 'Santiago de Querétaro'),
    Subdivision(name: 'Quintana Roo', capital: 'Chetumal'),
    Subdivision(name: 'San Luis Potosí', capital: 'San Luis Potosí'),
    Subdivision(name: 'Sinaloa', capital: 'Culiacán'),
    Subdivision(name: 'Sonora', capital: 'Hermosillo'),
    Subdivision(name: 'Tabasco', capital: 'Villahermosa'),
    Subdivision(name: 'Tamaulipas', capital: 'Ciudad Victoria'),
    Subdivision(name: 'Tlaxcala', capital: 'Tlaxcala de Xicohténcatl'),
    Subdivision(name: 'Veracruz', capital: 'Xalapa'),
    Subdivision(name: 'Yucatán', capital: 'Mérida'),
    Subdivision(name: 'Zacatecas', capital: 'Zacatecas'),
  ],

  // ═══ BRAZIL — 26 states + DF ═══
  'BR': [
    Subdivision(name: 'Acre', capital: 'Rio Branco'),
    Subdivision(name: 'Alagoas', capital: 'Maceió'),
    Subdivision(name: 'Amapá', capital: 'Macapá'),
    Subdivision(name: 'Amazonas', capital: 'Manaus'),
    Subdivision(name: 'Bahia', capital: 'Salvador'),
    Subdivision(name: 'Ceará', capital: 'Fortaleza'),
    Subdivision(name: 'Federal District', capital: 'Brasília'),
    Subdivision(name: 'Espírito Santo', capital: 'Vitória'),
    Subdivision(name: 'Goiás', capital: 'Goiânia'),
    Subdivision(name: 'Maranhão', capital: 'São Luís'),
    Subdivision(name: 'Mato Grosso', capital: 'Cuiabá'),
    Subdivision(name: 'Mato Grosso do Sul', capital: 'Campo Grande'),
    Subdivision(name: 'Minas Gerais', capital: 'Belo Horizonte'),
    Subdivision(name: 'Pará', capital: 'Belém'),
    Subdivision(name: 'Paraíba', capital: 'João Pessoa'),
    Subdivision(name: 'Paraná', capital: 'Curitiba'),
    Subdivision(name: 'Pernambuco', capital: 'Recife'),
    Subdivision(name: 'Piauí', capital: 'Teresina'),
    Subdivision(name: 'Rio de Janeiro', capital: 'Rio de Janeiro'),
    Subdivision(name: 'Rio Grande do Norte', capital: 'Natal'),
    Subdivision(name: 'Rio Grande do Sul', capital: 'Porto Alegre'),
    Subdivision(name: 'Rondônia', capital: 'Porto Velho'),
    Subdivision(name: 'Roraima', capital: 'Boa Vista'),
    Subdivision(name: 'Santa Catarina', capital: 'Florianópolis'),
    Subdivision(name: 'São Paulo', capital: 'São Paulo'),
    Subdivision(name: 'Sergipe', capital: 'Aracaju'),
    Subdivision(name: 'Tocantins', capital: 'Palmas'),
  ],

  // ═══ GERMANY — 16 states ═══
  'DE': [
    Subdivision(name: 'Baden-Württemberg', capital: 'Stuttgart'),
    Subdivision(name: 'Bavaria', capital: 'Munich'),
    Subdivision(name: 'Berlin', capital: 'Berlin'),
    Subdivision(name: 'Brandenburg', capital: 'Potsdam'),
    Subdivision(name: 'Bremen', capital: 'Bremen'),
    Subdivision(name: 'Hamburg', capital: 'Hamburg'),
    Subdivision(name: 'Hesse', capital: 'Wiesbaden'),
    Subdivision(name: 'Lower Saxony', capital: 'Hanover'),
    Subdivision(name: 'Mecklenburg-Vorpommern', capital: 'Schwerin'),
    Subdivision(name: 'North Rhine-Westphalia', capital: 'Düsseldorf'),
    Subdivision(name: 'Rhineland-Palatinate', capital: 'Mainz'),
    Subdivision(name: 'Saarland', capital: 'Saarbrücken'),
    Subdivision(name: 'Saxony', capital: 'Dresden'),
    Subdivision(name: 'Saxony-Anhalt', capital: 'Magdeburg'),
    Subdivision(name: 'Schleswig-Holstein', capital: 'Kiel'),
    Subdivision(name: 'Thuringia', capital: 'Erfurt'),
  ],

  // ═══ FRANCE — 13 metropolitan regions ═══
  'FR': [
    Subdivision(name: 'Auvergne-Rhône-Alpes', capital: 'Lyon'),
    Subdivision(name: 'Bourgogne-Franche-Comté', capital: 'Dijon'),
    Subdivision(name: 'Brittany', capital: 'Rennes'),
    Subdivision(name: 'Centre-Val de Loire', capital: 'Orléans'),
    Subdivision(name: 'Corsica', capital: 'Ajaccio'),
    Subdivision(name: 'Grand Est', capital: 'Strasbourg'),
    Subdivision(name: 'Hauts-de-France', capital: 'Lille'),
    Subdivision(name: 'Île-de-France', capital: 'Paris'),
    Subdivision(name: 'Normandy', capital: 'Rouen'),
    Subdivision(name: 'Nouvelle-Aquitaine', capital: 'Bordeaux'),
    Subdivision(name: 'Occitanie', capital: 'Toulouse'),
    Subdivision(name: 'Pays de la Loire', capital: 'Nantes'),
    Subdivision(name: 'Provence-Alpes-Côte d\'Azur', capital: 'Marseille'),
  ],

  // ═══ CHINA — 23 provinces + 4 municipalities + 5 autonomous regions ═══
  'CN': [
    Subdivision(name: 'Anhui', capital: 'Hefei'),
    Subdivision(name: 'Beijing', capital: 'Beijing'),
    Subdivision(name: 'Chongqing', capital: 'Chongqing'),
    Subdivision(name: 'Fujian', capital: 'Fuzhou'),
    Subdivision(name: 'Gansu', capital: 'Lanzhou'),
    Subdivision(name: 'Guangdong', capital: 'Guangzhou'),
    Subdivision(name: 'Guangxi', capital: 'Nanning'),
    Subdivision(name: 'Guizhou', capital: 'Guiyang'),
    Subdivision(name: 'Hainan', capital: 'Haikou'),
    Subdivision(name: 'Hebei', capital: 'Shijiazhuang'),
    Subdivision(name: 'Heilongjiang', capital: 'Harbin'),
    Subdivision(name: 'Henan', capital: 'Zhengzhou'),
    Subdivision(name: 'Hubei', capital: 'Wuhan'),
    Subdivision(name: 'Hunan', capital: 'Changsha'),
    Subdivision(name: 'Inner Mongolia', capital: 'Hohhot'),
    Subdivision(name: 'Jiangsu', capital: 'Nanjing'),
    Subdivision(name: 'Jiangxi', capital: 'Nanchang'),
    Subdivision(name: 'Jilin', capital: 'Changchun'),
    Subdivision(name: 'Liaoning', capital: 'Shenyang'),
    Subdivision(name: 'Ningxia', capital: 'Yinchuan'),
    Subdivision(name: 'Qinghai', capital: 'Xining'),
    Subdivision(name: 'Shaanxi', capital: 'Xi\'an'),
    Subdivision(name: 'Shandong', capital: 'Jinan'),
    Subdivision(name: 'Shanghai', capital: 'Shanghai'),
    Subdivision(name: 'Shanxi', capital: 'Taiyuan'),
    Subdivision(name: 'Sichuan', capital: 'Chengdu'),
    Subdivision(name: 'Tianjin', capital: 'Tianjin'),
    Subdivision(name: 'Tibet', capital: 'Lhasa'),
    Subdivision(name: 'Xinjiang', capital: 'Ürümqi'),
    Subdivision(name: 'Yunnan', capital: 'Kunming'),
    Subdivision(name: 'Zhejiang', capital: 'Hangzhou'),
  ],

  // ═══ JAPAN — 47 prefectures ═══
  'JP': [
    Subdivision(name: 'Hokkaido', capital: 'Sapporo'),
    Subdivision(name: 'Aomori', capital: 'Aomori'),
    Subdivision(name: 'Iwate', capital: 'Morioka'),
    Subdivision(name: 'Miyagi', capital: 'Sendai'),
    Subdivision(name: 'Akita', capital: 'Akita'),
    Subdivision(name: 'Yamagata', capital: 'Yamagata'),
    Subdivision(name: 'Fukushima', capital: 'Fukushima'),
    Subdivision(name: 'Ibaraki', capital: 'Mito'),
    Subdivision(name: 'Tochigi', capital: 'Utsunomiya'),
    Subdivision(name: 'Gunma', capital: 'Maebashi'),
    Subdivision(name: 'Saitama', capital: 'Saitama'),
    Subdivision(name: 'Chiba', capital: 'Chiba'),
    Subdivision(name: 'Tokyo', capital: 'Shinjuku'),
    Subdivision(name: 'Kanagawa', capital: 'Yokohama'),
    Subdivision(name: 'Niigata', capital: 'Niigata'),
    Subdivision(name: 'Toyama', capital: 'Toyama'),
    Subdivision(name: 'Ishikawa', capital: 'Kanazawa'),
    Subdivision(name: 'Fukui', capital: 'Fukui'),
    Subdivision(name: 'Yamanashi', capital: 'Kōfu'),
    Subdivision(name: 'Nagano', capital: 'Nagano'),
    Subdivision(name: 'Gifu', capital: 'Gifu'),
    Subdivision(name: 'Shizuoka', capital: 'Shizuoka'),
    Subdivision(name: 'Aichi', capital: 'Nagoya'),
    Subdivision(name: 'Mie', capital: 'Tsu'),
    Subdivision(name: 'Shiga', capital: 'Ōtsu'),
    Subdivision(name: 'Kyoto', capital: 'Kyoto'),
    Subdivision(name: 'Osaka', capital: 'Osaka'),
    Subdivision(name: 'Hyōgo', capital: 'Kobe'),
    Subdivision(name: 'Nara', capital: 'Nara'),
    Subdivision(name: 'Wakayama', capital: 'Wakayama'),
    Subdivision(name: 'Tottori', capital: 'Tottori'),
    Subdivision(name: 'Shimane', capital: 'Matsue'),
    Subdivision(name: 'Okayama', capital: 'Okayama'),
    Subdivision(name: 'Hiroshima', capital: 'Hiroshima'),
    Subdivision(name: 'Yamaguchi', capital: 'Yamaguchi'),
    Subdivision(name: 'Tokushima', capital: 'Tokushima'),
    Subdivision(name: 'Kagawa', capital: 'Takamatsu'),
    Subdivision(name: 'Ehime', capital: 'Matsuyama'),
    Subdivision(name: 'Kōchi', capital: 'Kōchi'),
    Subdivision(name: 'Fukuoka', capital: 'Fukuoka'),
    Subdivision(name: 'Saga', capital: 'Saga'),
    Subdivision(name: 'Nagasaki', capital: 'Nagasaki'),
    Subdivision(name: 'Kumamoto', capital: 'Kumamoto'),
    Subdivision(name: 'Ōita', capital: 'Ōita'),
    Subdivision(name: 'Miyazaki', capital: 'Miyazaki'),
    Subdivision(name: 'Kagoshima', capital: 'Kagoshima'),
    Subdivision(name: 'Okinawa', capital: 'Naha'),
  ],

  // ═══ RUSSIA — major federal subjects ═══
  'RU': [
    Subdivision(name: 'Moscow', capital: 'Moscow'),
    Subdivision(name: 'Saint Petersburg', capital: 'Saint Petersburg'),
    Subdivision(name: 'Moscow Oblast', capital: 'Krasnogorsk'),
    Subdivision(name: 'Sverdlovsk Oblast', capital: 'Yekaterinburg'),
    Subdivision(name: 'Novosibirsk Oblast', capital: 'Novosibirsk'),
    Subdivision(name: 'Tatarstan', capital: 'Kazan'),
    Subdivision(name: 'Chelyabinsk Oblast', capital: 'Chelyabinsk'),
    Subdivision(name: 'Nizhny Novgorod Oblast', capital: 'Nizhny Novgorod'),
    Subdivision(name: 'Samara Oblast', capital: 'Samara'),
    Subdivision(name: 'Krasnodar Krai', capital: 'Krasnodar'),
    Subdivision(name: 'Bashkortostan', capital: 'Ufa'),
    Subdivision(name: 'Krasnoyarsk Krai', capital: 'Krasnoyarsk'),
  ],

  // ═══ SOUTH KOREA — 17 divisions ═══
  'KR': [
    Subdivision(name: 'Seoul', capital: 'Seoul'),
    Subdivision(name: 'Busan', capital: 'Busan'),
    Subdivision(name: 'Incheon', capital: 'Incheon'),
    Subdivision(name: 'Daegu', capital: 'Daegu'),
    Subdivision(name: 'Daejeon', capital: 'Daejeon'),
    Subdivision(name: 'Gwangju', capital: 'Gwangju'),
    Subdivision(name: 'Ulsan', capital: 'Ulsan'),
    Subdivision(name: 'Sejong', capital: 'Sejong'),
    Subdivision(name: 'Gyeonggi', capital: 'Suwon'),
    Subdivision(name: 'Gangwon', capital: 'Chuncheon'),
    Subdivision(name: 'North Chungcheong', capital: 'Cheongju'),
    Subdivision(name: 'South Chungcheong', capital: 'Hongseong'),
    Subdivision(name: 'North Jeolla', capital: 'Jeonju'),
    Subdivision(name: 'South Jeolla', capital: 'Muan'),
    Subdivision(name: 'North Gyeongsang', capital: 'Andong'),
    Subdivision(name: 'South Gyeongsang', capital: 'Changwon'),
    Subdivision(name: 'Jeju', capital: 'Jeju City'),
  ],

  // ═══ SPAIN — 17 autonomous communities ═══
  'ES': [
    Subdivision(name: 'Andalusia', capital: 'Seville'),
    Subdivision(name: 'Aragon', capital: 'Zaragoza'),
    Subdivision(name: 'Asturias', capital: 'Oviedo'),
    Subdivision(name: 'Balearic Islands', capital: 'Palma'),
    Subdivision(name: 'Basque Country', capital: 'Vitoria-Gasteiz'),
    Subdivision(name: 'Canary Islands', capital: 'Las Palmas / Santa Cruz'),
    Subdivision(name: 'Cantabria', capital: 'Santander'),
    Subdivision(name: 'Castile and León', capital: 'Valladolid'),
    Subdivision(name: 'Castilla-La Mancha', capital: 'Toledo'),
    Subdivision(name: 'Catalonia', capital: 'Barcelona'),
    Subdivision(name: 'Extremadura', capital: 'Mérida'),
    Subdivision(name: 'Galicia', capital: 'Santiago de Compostela'),
    Subdivision(name: 'La Rioja', capital: 'Logroño'),
    Subdivision(name: 'Community of Madrid', capital: 'Madrid'),
    Subdivision(name: 'Murcia', capital: 'Murcia'),
    Subdivision(name: 'Navarre', capital: 'Pamplona'),
    Subdivision(name: 'Valencian Community', capital: 'Valencia'),
  ],

  // ═══ ITALY — 20 regions ═══
  'IT': [
    Subdivision(name: 'Abruzzo', capital: 'L\'Aquila'),
    Subdivision(name: 'Aosta Valley', capital: 'Aosta'),
    Subdivision(name: 'Apulia', capital: 'Bari'),
    Subdivision(name: 'Basilicata', capital: 'Potenza'),
    Subdivision(name: 'Calabria', capital: 'Catanzaro'),
    Subdivision(name: 'Campania', capital: 'Naples'),
    Subdivision(name: 'Emilia-Romagna', capital: 'Bologna'),
    Subdivision(name: 'Friuli Venezia Giulia', capital: 'Trieste'),
    Subdivision(name: 'Lazio', capital: 'Rome'),
    Subdivision(name: 'Liguria', capital: 'Genoa'),
    Subdivision(name: 'Lombardy', capital: 'Milan'),
    Subdivision(name: 'Marche', capital: 'Ancona'),
    Subdivision(name: 'Molise', capital: 'Campobasso'),
    Subdivision(name: 'Piedmont', capital: 'Turin'),
    Subdivision(name: 'Sardinia', capital: 'Cagliari'),
    Subdivision(name: 'Sicily', capital: 'Palermo'),
    Subdivision(name: 'Trentino-South Tyrol', capital: 'Trento'),
    Subdivision(name: 'Tuscany', capital: 'Florence'),
    Subdivision(name: 'Umbria', capital: 'Perugia'),
    Subdivision(name: 'Veneto', capital: 'Venice'),
  ],

  // ═══ NIGERIA — 36 states + FCT ═══
  'NG': [
    Subdivision(name: 'Abia', capital: 'Umuahia'),
    Subdivision(name: 'Adamawa', capital: 'Yola'),
    Subdivision(name: 'Akwa Ibom', capital: 'Uyo'),
    Subdivision(name: 'Anambra', capital: 'Awka'),
    Subdivision(name: 'Bauchi', capital: 'Bauchi'),
    Subdivision(name: 'Bayelsa', capital: 'Yenagoa'),
    Subdivision(name: 'Benue', capital: 'Makurdi'),
    Subdivision(name: 'Borno', capital: 'Maiduguri'),
    Subdivision(name: 'Cross River', capital: 'Calabar'),
    Subdivision(name: 'Delta', capital: 'Asaba'),
    Subdivision(name: 'Ebonyi', capital: 'Abakaliki'),
    Subdivision(name: 'Edo', capital: 'Benin City'),
    Subdivision(name: 'Ekiti', capital: 'Ado-Ekiti'),
    Subdivision(name: 'Enugu', capital: 'Enugu'),
    Subdivision(name: 'Federal Capital Territory', capital: 'Abuja'),
    Subdivision(name: 'Gombe', capital: 'Gombe'),
    Subdivision(name: 'Imo', capital: 'Owerri'),
    Subdivision(name: 'Jigawa', capital: 'Dutse'),
    Subdivision(name: 'Kaduna', capital: 'Kaduna'),
    Subdivision(name: 'Kano', capital: 'Kano'),
    Subdivision(name: 'Katsina', capital: 'Katsina'),
    Subdivision(name: 'Kebbi', capital: 'Birnin Kebbi'),
    Subdivision(name: 'Kogi', capital: 'Lokoja'),
    Subdivision(name: 'Kwara', capital: 'Ilorin'),
    Subdivision(name: 'Lagos', capital: 'Ikeja'),
    Subdivision(name: 'Nasarawa', capital: 'Lafia'),
    Subdivision(name: 'Niger', capital: 'Minna'),
    Subdivision(name: 'Ogun', capital: 'Abeokuta'),
    Subdivision(name: 'Ondo', capital: 'Akure'),
    Subdivision(name: 'Osun', capital: 'Osogbo'),
    Subdivision(name: 'Oyo', capital: 'Ibadan'),
    Subdivision(name: 'Plateau', capital: 'Jos'),
    Subdivision(name: 'Rivers', capital: 'Port Harcourt'),
    Subdivision(name: 'Sokoto', capital: 'Sokoto'),
    Subdivision(name: 'Taraba', capital: 'Jalingo'),
    Subdivision(name: 'Yobe', capital: 'Damaturu'),
    Subdivision(name: 'Zamfara', capital: 'Gusau'),
  ],

  // ═══ PAKISTAN — provinces + territories ═══
  'PK': [
    Subdivision(name: 'Punjab', capital: 'Lahore'),
    Subdivision(name: 'Sindh', capital: 'Karachi'),
    Subdivision(name: 'Khyber Pakhtunkhwa', capital: 'Peshawar'),
    Subdivision(name: 'Balochistan', capital: 'Quetta'),
    Subdivision(name: 'Islamabad Capital Territory', capital: 'Islamabad'),
    Subdivision(name: 'Gilgit-Baltistan', capital: 'Gilgit'),
    Subdivision(name: 'Azad Kashmir', capital: 'Muzaffarabad'),
  ],

  // ═══ SOUTH AFRICA — 9 provinces ═══
  'ZA': [
    Subdivision(name: 'Eastern Cape', capital: 'Bhisho'),
    Subdivision(name: 'Free State', capital: 'Bloemfontein'),
    Subdivision(name: 'Gauteng', capital: 'Johannesburg'),
    Subdivision(name: 'KwaZulu-Natal', capital: 'Pietermaritzburg'),
    Subdivision(name: 'Limpopo', capital: 'Polokwane'),
    Subdivision(name: 'Mpumalanga', capital: 'Mbombela'),
    Subdivision(name: 'North West', capital: 'Mahikeng'),
    Subdivision(name: 'Northern Cape', capital: 'Kimberley'),
    Subdivision(name: 'Western Cape', capital: 'Cape Town'),
  ],

  // ═══ EGYPT — 27 governorates ═══
  'EG': [
    Subdivision(name: 'Cairo', capital: 'Cairo'),
    Subdivision(name: 'Alexandria', capital: 'Alexandria'),
    Subdivision(name: 'Giza', capital: 'Giza'),
    Subdivision(name: 'Qalyubia', capital: 'Benha'),
    Subdivision(name: 'Port Said', capital: 'Port Said'),
    Subdivision(name: 'Suez', capital: 'Suez'),
    Subdivision(name: 'Luxor', capital: 'Luxor'),
    Subdivision(name: 'Aswan', capital: 'Aswan'),
    Subdivision(name: 'Asyut', capital: 'Asyut'),
    Subdivision(name: 'Beheira', capital: 'Damanhur'),
    Subdivision(name: 'Beni Suef', capital: 'Beni Suef'),
    Subdivision(name: 'Dakahlia', capital: 'Mansoura'),
    Subdivision(name: 'Damietta', capital: 'Damietta'),
    Subdivision(name: 'Faiyum', capital: 'Faiyum'),
    Subdivision(name: 'Gharbia', capital: 'Tanta'),
    Subdivision(name: 'Ismailia', capital: 'Ismailia'),
    Subdivision(name: 'Kafr El Sheikh', capital: 'Kafr El Sheikh'),
    Subdivision(name: 'Matrouh', capital: 'Mersa Matruh'),
    Subdivision(name: 'Minya', capital: 'Minya'),
    Subdivision(name: 'Monufia', capital: 'Shibin El Kom'),
    Subdivision(name: 'New Valley', capital: 'Kharga'),
    Subdivision(name: 'North Sinai', capital: 'Arish'),
    Subdivision(name: 'Qena', capital: 'Qena'),
    Subdivision(name: 'Red Sea', capital: 'Hurghada'),
    Subdivision(name: 'Sharqia', capital: 'Zagazig'),
    Subdivision(name: 'Sohag', capital: 'Sohag'),
    Subdivision(name: 'South Sinai', capital: 'El-Tor'),
  ],

  // ═══ INDONESIA — 38 provinces ═══
  'ID': [
    Subdivision(name: 'Aceh', capital: 'Banda Aceh'),
    Subdivision(name: 'Bali', capital: 'Denpasar'),
    Subdivision(name: 'Banten', capital: 'Serang'),
    Subdivision(name: 'Bengkulu', capital: 'Bengkulu'),
    Subdivision(name: 'Central Java', capital: 'Semarang'),
    Subdivision(name: 'Central Kalimantan', capital: 'Palangka Raya'),
    Subdivision(name: 'Central Sulawesi', capital: 'Palu'),
    Subdivision(name: 'East Java', capital: 'Surabaya'),
    Subdivision(name: 'East Kalimantan', capital: 'Samarinda'),
    Subdivision(name: 'East Nusa Tenggara', capital: 'Kupang'),
    Subdivision(name: 'Jakarta', capital: 'Jakarta'),
    Subdivision(name: 'Jambi', capital: 'Jambi'),
    Subdivision(name: 'Lampung', capital: 'Bandar Lampung'),
    Subdivision(name: 'North Kalimantan', capital: 'Tanjung Selor'),
    Subdivision(name: 'North Maluku', capital: 'Sofifi'),
    Subdivision(name: 'North Sulawesi', capital: 'Manado'),
    Subdivision(name: 'North Sumatra', capital: 'Medan'),
    Subdivision(name: 'Papua', capital: 'Jayapura'),
    Subdivision(name: 'Riau', capital: 'Pekanbaru'),
    Subdivision(name: 'South Kalimantan', capital: 'Banjarbaru'),
    Subdivision(name: 'South Sulawesi', capital: 'Makassar'),
    Subdivision(name: 'South Sumatra', capital: 'Palembang'),
    Subdivision(name: 'Southeast Sulawesi', capital: 'Kendari'),
    Subdivision(name: 'West Java', capital: 'Bandung'),
    Subdivision(name: 'West Kalimantan', capital: 'Pontianak'),
    Subdivision(name: 'West Nusa Tenggara', capital: 'Mataram'),
    Subdivision(name: 'West Papua', capital: 'Manokwari'),
    Subdivision(name: 'West Sulawesi', capital: 'Mamuju'),
    Subdivision(name: 'West Sumatra', capital: 'Padang'),
    Subdivision(name: 'Yogyakarta', capital: 'Yogyakarta'),
  ],

  // ═══ TURKEY — 7 regions ═══
  'TR': [
    Subdivision(name: 'Marmara', capital: 'Istanbul'),
    Subdivision(name: 'Central Anatolia', capital: 'Ankara'),
    Subdivision(name: 'Aegean', capital: 'Izmir'),
    Subdivision(name: 'Mediterranean', capital: 'Antalya'),
    Subdivision(name: 'Black Sea', capital: 'Trabzon'),
    Subdivision(name: 'Eastern Anatolia', capital: 'Erzurum'),
    Subdivision(name: 'Southeastern Anatolia', capital: 'Gaziantep'),
  ],

  // ═══ THAILAND — 6 regions ═══
  'TH': [
    Subdivision(name: 'Bangkok', capital: 'Bangkok'),
    Subdivision(name: 'Central Thailand', capital: 'Nakhon Pathom'),
    Subdivision(name: 'Eastern Thailand', capital: 'Chonburi'),
    Subdivision(name: 'Northern Thailand', capital: 'Chiang Mai'),
    Subdivision(name: 'Northeastern Thailand', capital: 'Nakhon Ratchasima'),
    Subdivision(name: 'Southern Thailand', capital: 'Surat Thani'),
  ],

  // ═══ PHILIPPINES — 17 regions ═══
  'PH': [
    Subdivision(name: 'National Capital Region', capital: 'Manila'),
    Subdivision(name: 'Cordillera', capital: 'Baguio'),
    Subdivision(name: 'Ilocos', capital: 'San Fernando'),
    Subdivision(name: 'Cagayan Valley', capital: 'Tuguegarao'),
    Subdivision(name: 'Central Luzon', capital: 'San Fernando'),
    Subdivision(name: 'Calabarzon', capital: 'Calamba'),
    Subdivision(name: 'Mimaropa', capital: 'Calapan'),
    Subdivision(name: 'Bicol', capital: 'Legazpi'),
    Subdivision(name: 'Western Visayas', capital: 'Iloilo City'),
    Subdivision(name: 'Central Visayas', capital: 'Cebu City'),
    Subdivision(name: 'Eastern Visayas', capital: 'Tacloban'),
    Subdivision(name: 'Zamboanga Peninsula', capital: 'Pagadian'),
    Subdivision(name: 'Northern Mindanao', capital: 'Cagayan de Oro'),
    Subdivision(name: 'Davao', capital: 'Davao City'),
    Subdivision(name: 'Soccsksargen', capital: 'Koronadal'),
    Subdivision(name: 'Caraga', capital: 'Butuan'),
    Subdivision(name: 'Bangsamoro', capital: 'Cotabato City'),
  ],

  // ═══ ARGENTINA — 23 provinces + CABA ═══
  'AR': [
    Subdivision(name: 'Buenos Aires', capital: 'La Plata'),
    Subdivision(name: 'Buenos Aires City', capital: 'Buenos Aires'),
    Subdivision(name: 'Catamarca', capital: 'San Fernando del Valle de Catamarca'),
    Subdivision(name: 'Chaco', capital: 'Resistencia'),
    Subdivision(name: 'Chubut', capital: 'Rawson'),
    Subdivision(name: 'Córdoba', capital: 'Córdoba'),
    Subdivision(name: 'Corrientes', capital: 'Corrientes'),
    Subdivision(name: 'Entre Ríos', capital: 'Paraná'),
    Subdivision(name: 'Formosa', capital: 'Formosa'),
    Subdivision(name: 'Jujuy', capital: 'San Salvador de Jujuy'),
    Subdivision(name: 'La Pampa', capital: 'Santa Rosa'),
    Subdivision(name: 'La Rioja', capital: 'La Rioja'),
    Subdivision(name: 'Mendoza', capital: 'Mendoza'),
    Subdivision(name: 'Misiones', capital: 'Posadas'),
    Subdivision(name: 'Neuquén', capital: 'Neuquén'),
    Subdivision(name: 'Río Negro', capital: 'Viedma'),
    Subdivision(name: 'Salta', capital: 'Salta'),
    Subdivision(name: 'San Juan', capital: 'San Juan'),
    Subdivision(name: 'San Luis', capital: 'San Luis'),
    Subdivision(name: 'Santa Cruz', capital: 'Río Gallegos'),
    Subdivision(name: 'Santa Fe', capital: 'Santa Fe'),
    Subdivision(name: 'Santiago del Estero', capital: 'Santiago del Estero'),
    Subdivision(name: 'Tierra del Fuego', capital: 'Ushuaia'),
    Subdivision(name: 'Tucumán', capital: 'San Miguel de Tucumán'),
  ],

  // ═══ COLOMBIA — 32 departments + Capital ═══
  'CO': [
    Subdivision(name: 'Amazonas', capital: 'Leticia'),
    Subdivision(name: 'Antioquia', capital: 'Medellín'),
    Subdivision(name: 'Arauca', capital: 'Arauca'),
    Subdivision(name: 'Atlántico', capital: 'Barranquilla'),
    Subdivision(name: 'Bogotá D.C.', capital: 'Bogotá'),
    Subdivision(name: 'Bolívar', capital: 'Cartagena'),
    Subdivision(name: 'Boyacá', capital: 'Tunja'),
    Subdivision(name: 'Caldas', capital: 'Manizales'),
    Subdivision(name: 'Caquetá', capital: 'Florencia'),
    Subdivision(name: 'Casanare', capital: 'Yopal'),
    Subdivision(name: 'Cauca', capital: 'Popayán'),
    Subdivision(name: 'Cesar', capital: 'Valledupar'),
    Subdivision(name: 'Chocó', capital: 'Quibdó'),
    Subdivision(name: 'Córdoba', capital: 'Montería'),
    Subdivision(name: 'Cundinamarca', capital: 'Bogotá'),
    Subdivision(name: 'Guainía', capital: 'Inírida'),
    Subdivision(name: 'Guaviare', capital: 'San José del Guaviare'),
    Subdivision(name: 'Huila', capital: 'Neiva'),
    Subdivision(name: 'La Guajira', capital: 'Riohacha'),
    Subdivision(name: 'Magdalena', capital: 'Santa Marta'),
    Subdivision(name: 'Meta', capital: 'Villavicencio'),
    Subdivision(name: 'Nariño', capital: 'Pasto'),
    Subdivision(name: 'Norte de Santander', capital: 'Cúcuta'),
    Subdivision(name: 'Putumayo', capital: 'Mocoa'),
    Subdivision(name: 'Quindío', capital: 'Armenia'),
    Subdivision(name: 'Risaralda', capital: 'Pereira'),
    Subdivision(name: 'Santander', capital: 'Bucaramanga'),
    Subdivision(name: 'Sucre', capital: 'Sincelejo'),
    Subdivision(name: 'Tolima', capital: 'Ibagué'),
    Subdivision(name: 'Valle del Cauca', capital: 'Cali'),
    Subdivision(name: 'Vaupés', capital: 'Mitú'),
    Subdivision(name: 'Vichada', capital: 'Puerto Carreño'),
  ],

  // ═══ PERU — 25 regions ═══
  'PE': [
    Subdivision(name: 'Amazonas', capital: 'Chachapoyas'),
    Subdivision(name: 'Áncash', capital: 'Huaraz'),
    Subdivision(name: 'Apurímac', capital: 'Abancay'),
    Subdivision(name: 'Arequipa', capital: 'Arequipa'),
    Subdivision(name: 'Ayacucho', capital: 'Ayacucho'),
    Subdivision(name: 'Cajamarca', capital: 'Cajamarca'),
    Subdivision(name: 'Callao', capital: 'Callao'),
    Subdivision(name: 'Cusco', capital: 'Cusco'),
    Subdivision(name: 'Huancavelica', capital: 'Huancavelica'),
    Subdivision(name: 'Huánuco', capital: 'Huánuco'),
    Subdivision(name: 'Ica', capital: 'Ica'),
    Subdivision(name: 'Junín', capital: 'Huancayo'),
    Subdivision(name: 'La Libertad', capital: 'Trujillo'),
    Subdivision(name: 'Lambayeque', capital: 'Chiclayo'),
    Subdivision(name: 'Lima', capital: 'Lima'),
    Subdivision(name: 'Loreto', capital: 'Iquitos'),
    Subdivision(name: 'Madre de Dios', capital: 'Puerto Maldonado'),
    Subdivision(name: 'Moquegua', capital: 'Moquegua'),
    Subdivision(name: 'Pasco', capital: 'Cerro de Pasco'),
    Subdivision(name: 'Piura', capital: 'Piura'),
    Subdivision(name: 'Puno', capital: 'Puno'),
    Subdivision(name: 'San Martín', capital: 'Moyobamba'),
    Subdivision(name: 'Tacna', capital: 'Tacna'),
    Subdivision(name: 'Tumbes', capital: 'Tumbes'),
    Subdivision(name: 'Ucayali', capital: 'Pucallpa'),
  ],

  // ═══ CHILE — 16 regions ═══
  'CL': [
    Subdivision(name: 'Arica y Parinacota', capital: 'Arica'),
    Subdivision(name: 'Tarapacá', capital: 'Iquique'),
    Subdivision(name: 'Antofagasta', capital: 'Antofagasta'),
    Subdivision(name: 'Atacama', capital: 'Copiapó'),
    Subdivision(name: 'Coquimbo', capital: 'La Serena'),
    Subdivision(name: 'Valparaíso', capital: 'Valparaíso'),
    Subdivision(name: 'Santiago Metropolitan', capital: 'Santiago'),
    Subdivision(name: 'O\'Higgins', capital: 'Rancagua'),
    Subdivision(name: 'Maule', capital: 'Talca'),
    Subdivision(name: 'Ñuble', capital: 'Chillán'),
    Subdivision(name: 'Biobío', capital: 'Concepción'),
    Subdivision(name: 'Araucanía', capital: 'Temuco'),
    Subdivision(name: 'Los Ríos', capital: 'Valdivia'),
    Subdivision(name: 'Los Lagos', capital: 'Puerto Montt'),
    Subdivision(name: 'Aysén', capital: 'Coyhaique'),
    Subdivision(name: 'Magallanes', capital: 'Punta Arenas'),
  ],

  // ═══ POLAND — 16 voivodeships ═══
  'PL': [
    Subdivision(name: 'Greater Poland', capital: 'Poznań'),
    Subdivision(name: 'Kuyavia-Pomerania', capital: 'Bydgoszcz'),
    Subdivision(name: 'Lesser Poland', capital: 'Kraków'),
    Subdivision(name: 'Łódź', capital: 'Łódź'),
    Subdivision(name: 'Lower Silesia', capital: 'Wrocław'),
    Subdivision(name: 'Lublin', capital: 'Lublin'),
    Subdivision(name: 'Lubusz', capital: 'Gorzów Wielkopolski'),
    Subdivision(name: 'Masovia', capital: 'Warsaw'),
    Subdivision(name: 'Opole', capital: 'Opole'),
    Subdivision(name: 'Podkarpacie', capital: 'Rzeszów'),
    Subdivision(name: 'Podlasie', capital: 'Białystok'),
    Subdivision(name: 'Pomerania', capital: 'Gdańsk'),
    Subdivision(name: 'Silesia', capital: 'Katowice'),
    Subdivision(name: 'Świętokrzyskie', capital: 'Kielce'),
    Subdivision(name: 'Warmia-Masuria', capital: 'Olsztyn'),
    Subdivision(name: 'West Pomerania', capital: 'Szczecin'),
  ],

  // ═══ UKRAINE — 24 oblasts + Kyiv ═══
  'UA': [
    Subdivision(name: 'Cherkasy', capital: 'Cherkasy'),
    Subdivision(name: 'Chernihiv', capital: 'Chernihiv'),
    Subdivision(name: 'Chernivtsi', capital: 'Chernivtsi'),
    Subdivision(name: 'Dnipropetrovsk', capital: 'Dnipro'),
    Subdivision(name: 'Donetsk', capital: 'Donetsk'),
    Subdivision(name: 'Ivano-Frankivsk', capital: 'Ivano-Frankivsk'),
    Subdivision(name: 'Kharkiv', capital: 'Kharkiv'),
    Subdivision(name: 'Kherson', capital: 'Kherson'),
    Subdivision(name: 'Khmelnytskyi', capital: 'Khmelnytskyi'),
    Subdivision(name: 'Kirovohrad', capital: 'Kropyvnytskyi'),
    Subdivision(name: 'Kyiv City', capital: 'Kyiv'),
    Subdivision(name: 'Kyiv Oblast', capital: 'Brovary'),
    Subdivision(name: 'Luhansk', capital: 'Luhansk'),
    Subdivision(name: 'Lviv', capital: 'Lviv'),
    Subdivision(name: 'Mykolaiv', capital: 'Mykolaiv'),
    Subdivision(name: 'Odesa', capital: 'Odesa'),
    Subdivision(name: 'Poltava', capital: 'Poltava'),
    Subdivision(name: 'Rivne', capital: 'Rivne'),
    Subdivision(name: 'Sumy', capital: 'Sumy'),
    Subdivision(name: 'Ternopil', capital: 'Ternopil'),
    Subdivision(name: 'Vinnytsia', capital: 'Vinnytsia'),
    Subdivision(name: 'Volyn', capital: 'Lutsk'),
    Subdivision(name: 'Zakarpattia', capital: 'Uzhhorod'),
    Subdivision(name: 'Zaporizhzhia', capital: 'Zaporizhzhia'),
    Subdivision(name: 'Zhytomyr', capital: 'Zhytomyr'),
  ],

  // ═══ SWEDEN — 21 counties ═══
  'SE': [
    Subdivision(name: 'Stockholm', capital: 'Stockholm'),
    Subdivision(name: 'Uppsala', capital: 'Uppsala'),
    Subdivision(name: 'Södermanland', capital: 'Nyköping'),
    Subdivision(name: 'Östergötland', capital: 'Linköping'),
    Subdivision(name: 'Jönköping', capital: 'Jönköping'),
    Subdivision(name: 'Kronoberg', capital: 'Växjö'),
    Subdivision(name: 'Kalmar', capital: 'Kalmar'),
    Subdivision(name: 'Gotland', capital: 'Visby'),
    Subdivision(name: 'Blekinge', capital: 'Karlskrona'),
    Subdivision(name: 'Skåne', capital: 'Malmö'),
    Subdivision(name: 'Halland', capital: 'Halmstad'),
    Subdivision(name: 'Västra Götaland', capital: 'Gothenburg'),
    Subdivision(name: 'Värmland', capital: 'Karlstad'),
    Subdivision(name: 'Örebro', capital: 'Örebro'),
    Subdivision(name: 'Västmanland', capital: 'Västerås'),
    Subdivision(name: 'Dalarna', capital: 'Falun'),
    Subdivision(name: 'Gävleborg', capital: 'Gävle'),
    Subdivision(name: 'Västernorrland', capital: 'Härnösand'),
    Subdivision(name: 'Jämtland', capital: 'Östersund'),
    Subdivision(name: 'Västerbotten', capital: 'Umeå'),
    Subdivision(name: 'Norrbotten', capital: 'Luleå'),
  ],

  // ═══ AUSTRIA — 9 states ═══
  'AT': [
    Subdivision(name: 'Burgenland', capital: 'Eisenstadt'),
    Subdivision(name: 'Carinthia', capital: 'Klagenfurt'),
    Subdivision(name: 'Lower Austria', capital: 'St. Pölten'),
    Subdivision(name: 'Salzburg', capital: 'Salzburg'),
    Subdivision(name: 'Styria', capital: 'Graz'),
    Subdivision(name: 'Tyrol', capital: 'Innsbruck'),
    Subdivision(name: 'Upper Austria', capital: 'Linz'),
    Subdivision(name: 'Vienna', capital: 'Vienna'),
    Subdivision(name: 'Vorarlberg', capital: 'Bregenz'),
  ],

  // ═══ SWITZERLAND — 26 cantons ═══
  'CH': [
    Subdivision(name: 'Zürich', capital: 'Zürich'),
    Subdivision(name: 'Bern', capital: 'Bern'),
    Subdivision(name: 'Lucerne', capital: 'Lucerne'),
    Subdivision(name: 'Uri', capital: 'Altdorf'),
    Subdivision(name: 'Schwyz', capital: 'Schwyz'),
    Subdivision(name: 'Obwalden', capital: 'Sarnen'),
    Subdivision(name: 'Nidwalden', capital: 'Stans'),
    Subdivision(name: 'Glarus', capital: 'Glarus'),
    Subdivision(name: 'Zug', capital: 'Zug'),
    Subdivision(name: 'Fribourg', capital: 'Fribourg'),
    Subdivision(name: 'Solothurn', capital: 'Solothurn'),
    Subdivision(name: 'Basel-Stadt', capital: 'Basel'),
    Subdivision(name: 'Basel-Landschaft', capital: 'Liestal'),
    Subdivision(name: 'Schaffhausen', capital: 'Schaffhausen'),
    Subdivision(name: 'Appenzell Ausserrhoden', capital: 'Herisau'),
    Subdivision(name: 'Appenzell Innerrhoden', capital: 'Appenzell'),
    Subdivision(name: 'St. Gallen', capital: 'St. Gallen'),
    Subdivision(name: 'Graubünden', capital: 'Chur'),
    Subdivision(name: 'Aargau', capital: 'Aarau'),
    Subdivision(name: 'Thurgau', capital: 'Frauenfeld'),
    Subdivision(name: 'Ticino', capital: 'Bellinzona'),
    Subdivision(name: 'Vaud', capital: 'Lausanne'),
    Subdivision(name: 'Valais', capital: 'Sion'),
    Subdivision(name: 'Neuchâtel', capital: 'Neuchâtel'),
    Subdivision(name: 'Geneva', capital: 'Geneva'),
    Subdivision(name: 'Jura', capital: 'Delémont'),
  ],

  // ═══ NETHERLANDS — 12 provinces ═══
  'NL': [
    Subdivision(name: 'Drenthe', capital: 'Assen'),
    Subdivision(name: 'Flevoland', capital: 'Lelystad'),
    Subdivision(name: 'Friesland', capital: 'Leeuwarden'),
    Subdivision(name: 'Gelderland', capital: 'Arnhem'),
    Subdivision(name: 'Groningen', capital: 'Groningen'),
    Subdivision(name: 'Limburg', capital: 'Maastricht'),
    Subdivision(name: 'North Brabant', capital: 'Den Bosch'),
    Subdivision(name: 'North Holland', capital: 'Haarlem'),
    Subdivision(name: 'Overijssel', capital: 'Zwolle'),
    Subdivision(name: 'South Holland', capital: 'The Hague'),
    Subdivision(name: 'Utrecht', capital: 'Utrecht'),
    Subdivision(name: 'Zeeland', capital: 'Middelburg'),
  ],

  // ═══ NEW ZEALAND — 16 regions ═══
  'NZ': [
    Subdivision(name: 'Northland', capital: 'Whangārei'),
    Subdivision(name: 'Auckland', capital: 'Auckland'),
    Subdivision(name: 'Waikato', capital: 'Hamilton'),
    Subdivision(name: 'Bay of Plenty', capital: 'Tauranga'),
    Subdivision(name: 'Gisborne', capital: 'Gisborne'),
    Subdivision(name: 'Hawke\'s Bay', capital: 'Napier'),
    Subdivision(name: 'Taranaki', capital: 'New Plymouth'),
    Subdivision(name: 'Manawatū-Whanganui', capital: 'Palmerston North'),
    Subdivision(name: 'Wellington', capital: 'Wellington'),
    Subdivision(name: 'Tasman', capital: 'Richmond'),
    Subdivision(name: 'Nelson', capital: 'Nelson'),
    Subdivision(name: 'Marlborough', capital: 'Blenheim'),
    Subdivision(name: 'West Coast', capital: 'Greymouth'),
    Subdivision(name: 'Canterbury', capital: 'Christchurch'),
    Subdivision(name: 'Otago', capital: 'Dunedin'),
    Subdivision(name: 'Southland', capital: 'Invercargill'),
  ],

  // ═══ VIETNAM — 8 regions ═══
  'VN': [
    Subdivision(name: 'Northwest', capital: 'Điện Biên Phủ'),
    Subdivision(name: 'Northeast', capital: 'Thái Nguyên'),
    Subdivision(name: 'Red River Delta', capital: 'Hanoi'),
    Subdivision(name: 'North Central Coast', capital: 'Vinh'),
    Subdivision(name: 'South Central Coast', capital: 'Đà Nẵng'),
    Subdivision(name: 'Central Highlands', capital: 'Buôn Ma Thuột'),
    Subdivision(name: 'Southeast', capital: 'Ho Chi Minh City'),
    Subdivision(name: 'Mekong Delta', capital: 'Cần Thơ'),
  ],

  // ═══ MALAYSIA — 13 states + 3 territories ═══
  'MY': [
    Subdivision(name: 'Johor', capital: 'Johor Bahru'),
    Subdivision(name: 'Kedah', capital: 'Alor Setar'),
    Subdivision(name: 'Kelantan', capital: 'Kota Bharu'),
    Subdivision(name: 'Malacca', capital: 'Malacca City'),
    Subdivision(name: 'Negeri Sembilan', capital: 'Seremban'),
    Subdivision(name: 'Pahang', capital: 'Kuantan'),
    Subdivision(name: 'Penang', capital: 'George Town'),
    Subdivision(name: 'Perak', capital: 'Ipoh'),
    Subdivision(name: 'Perlis', capital: 'Kangar'),
    Subdivision(name: 'Sabah', capital: 'Kota Kinabalu'),
    Subdivision(name: 'Sarawak', capital: 'Kuching'),
    Subdivision(name: 'Selangor', capital: 'Shah Alam'),
    Subdivision(name: 'Terengganu', capital: 'Kuala Terengganu'),
    Subdivision(name: 'Kuala Lumpur', capital: 'Kuala Lumpur'),
    Subdivision(name: 'Putrajaya', capital: 'Putrajaya'),
    Subdivision(name: 'Labuan', capital: 'Victoria'),
  ],

  // ═══ IRAN — 31 provinces ═══
  'IR': [
    Subdivision(name: 'Tehran', capital: 'Tehran'),
    Subdivision(name: 'Isfahan', capital: 'Isfahan'),
    Subdivision(name: 'Fars', capital: 'Shiraz'),
    Subdivision(name: 'Razavi Khorasan', capital: 'Mashhad'),
    Subdivision(name: 'East Azerbaijan', capital: 'Tabriz'),
    Subdivision(name: 'Khuzestan', capital: 'Ahvaz'),
    Subdivision(name: 'Kerman', capital: 'Kerman'),
    Subdivision(name: 'Mazandaran', capital: 'Sari'),
    Subdivision(name: 'Gilan', capital: 'Rasht'),
    Subdivision(name: 'Alborz', capital: 'Karaj'),
    Subdivision(name: 'Markazi', capital: 'Arak'),
    Subdivision(name: 'Hormozgan', capital: 'Bandar Abbas'),
    Subdivision(name: 'Kurdistan', capital: 'Sanandaj'),
    Subdivision(name: 'Lorestan', capital: 'Khorramabad'),
    Subdivision(name: 'Hamadan', capital: 'Hamadan'),
    Subdivision(name: 'West Azerbaijan', capital: 'Urmia'),
    Subdivision(name: 'Sistan and Baluchestan', capital: 'Zahedan'),
    Subdivision(name: 'Kermanshah', capital: 'Kermanshah'),
    Subdivision(name: 'Golestan', capital: 'Gorgan'),
    Subdivision(name: 'Qom', capital: 'Qom'),
    Subdivision(name: 'Yazd', capital: 'Yazd'),
    Subdivision(name: 'Zanjan', capital: 'Zanjan'),
    Subdivision(name: 'Ardabil', capital: 'Ardabil'),
    Subdivision(name: 'Bushehr', capital: 'Bushehr'),
    Subdivision(name: 'South Khorasan', capital: 'Birjand'),
    Subdivision(name: 'North Khorasan', capital: 'Bojnurd'),
    Subdivision(name: 'Semnan', capital: 'Semnan'),
    Subdivision(name: 'Qazvin', capital: 'Qazvin'),
    Subdivision(name: 'Chaharmahal and Bakhtiari', capital: 'Shahrekord'),
    Subdivision(name: 'Kohgiluyeh and Boyer-Ahmad', capital: 'Yasuj'),
    Subdivision(name: 'Ilam', capital: 'Ilam'),
  ],
};

/// Returns subdivisions for a country, or null if none exist.
List<Subdivision>? subdivisionsFor(String isoCode) =>
    allSubdivisions[isoCode.toUpperCase()];

/// Whether a country has subdivision data.
bool hasSubdivisions(String isoCode) =>
    allSubdivisions.containsKey(isoCode.toUpperCase());
